# Generated by Django 3.2.19 on 2023-05-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='KickBack', max_length=200, unique=True),
        ),
    ]
