# Generated by Django 3.2.19 on 2023-06-06 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=None, max_length=60, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
